export const THEMES = [
  "light",
  "dark",
  "cupcake",
  "bumblebee",
  "emerald",
  "corporate",
  "synthwave",
  "retro",
  "cyberpunk",
  "valentine",
  "halloween",
  "garden",
  "forest",
  "aqua",
  "lofi",
  "pastel",
  "fantasy",
  "wireframe",
  "black",
  "luxury",
  "dracula",
  "cmyk",
  "autumn",
  "business",
  "acid",
  "lemonade",
  "night",
  "coffee",
  "winter",
  "dim",
  "nord",
  "sunset",
];

export const themeToLogoMap = {
  light: '/logo_black.png',
  dark: '/logo_white.png',
  cupcake: '/logo_white.png',
  bumblebee: '/logo_black.png',
  emerald: '/logo_black.png',
  corporate: '/logo_black.png',
  synthwave: '/logo_white.png',
  retro: '/logo_white.png',
  cyberpunk: '/logo_white.png',
  valentine: '/logo_white.png',
  halloween: '/logo_white.png',
  garden: '/logo_black.png',
  forest: '/logo_black.png',
  aqua: '/logo_black.png',
  lofi: '/logo_black.png',
  pastel: '/logo_black.png',
  fantasy: '/logo_black.png',
  wireframe: '/logo_black.png',
  black: '/logo_white.png',
  luxury: '/logo_white.png',
  dracula: '/logo_white.png',
  cmyk: '/logo_black.png',
  autumn: '/logo_black.png',
  business: '/logo_black.png',
  acid: '/logo_black.png',
  lemonade: '/logo_black.png',
  night: '/logo_white.png',
  coffee: '/logo_black.png',
  winter: '/logo_black.png',
  dim: '/logo_black.png',
  nord: '/logo_black.png',
  sunset: '/logo_black.png',
};